# Generated by Django 5.1 on 2024-08-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_usertask_project_project_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='execution_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
